#!/bin/sh
# Firefox wrapper script for Xpra session
# This script allows us to control Firefox startup options when using --start=firefox

cd "$HOME"

# Set Firefox preferences for better Xpra integration
export MOZ_USE_XINPUT2=1
export MOZ_ENABLE_WAYLAND=0
export MOZ_DISABLE_RDD_SANDBOX=1
export MOZ_DISABLE_CONTENT_SANDBOX=1

# Create a custom Firefox profile for this session if it doesn't exist
PROFILE_DIR="$HOME/.firefox-launcher-profile"
if [ ! -d "$PROFILE_DIR" ]; then
    mkdir -p "$PROFILE_DIR"
    # Create a minimal user.js with our preferences
    cat > "$PROFILE_DIR/user.js" << EOF
// Firefox preferences for Xpra integration
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("dom.disable_open_during_load", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtab.preload", false);
EOF
fi

# Start Firefox with our custom options
exec firefox \
    --profile "$PROFILE_DIR" \
    --new-instance \
    --class=Firefox-Launcher \
    --name=Firefox-Launcher \
    --no-first-run \
    --no-default-browser-check \
    --disable-dev-shm-usage \
    --disable-gpu-sandbox \
    --disable-software-rasterizer \
    --disable-background-timer-throttling \
    --disable-renderer-backgrounding \
    --disable-backgrounding-occluded-windows \
    --remote-debugging-port=0 \
    --window-size=1280,800 \
    about:blank
